### ISSUE TITLE
What function gets the bot's last response?

### ISSUE THREAD

**Issue by simonnarang** [zmeyc/telegram-bot-swift#10]
😅 Haven't been able to find it

**Comment by zmeyc** [comment]
In 0.4.1?

**Comment by zmeyc** [comment]
Response to which request?

**Comment by simonnarang** [comment]
Yes in the latest version

**Comment by simonnarang** [comment]
I mean the last thing the bot sent to the user

**Comment by simonnarang** [comment]
like `lastMessage` but for the bot, not the user.

**Comment by zmeyc** [comment]
I guess this needs to be tracked by the bot itself. Once it's sent it's gone. :)
Also, bot can send different types of content to user, not only text, so it's hard to support this at library level.

Something like:
`
sessions[bot.lastMessage.chat.id] = "last phrase I sent"
`

I'll add sqlite example soon with example how data can be persisted in database.

**Comment by simonnarang** [comment]
Ok thanks
