### ISSUE TITLE
New package not showing up in Xcode dependencies

### ISSUE THREAD

**Issue by simonnarang** [zmeyc/telegram-bot-swift#11]
In `package.swift` I added `.Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 3)`
I then ran `swift build` in terminal and the package showed up in the sources folder in finder
However, in the dependencies tab of the Xcode project, Alamofire doesn't show up, and I can't import it into `main.swift` either. Is there a way to add it in build phases or something like that?

**Comment by zmeyc** [comment]
Regenerating the project should work: swift build -X
But Alamofire doesn't build with Swift 3, I tried adding it to example project but got a lot of compilation errors. I'm using raw NSURLSession + SwiftyJSON.

**Comment by zmeyc** [comment]
Btw I created a chat for discussing the SDK: https://telegram.me/swiftsdkchat
welcome :)

**Comment by simonnarang** [comment]
Thank you just figured that out.
