### ISSUE TITLE
Arguments.scanRestOfString() does not work at all on Linux

### ISSUE THREAD

**Issue by cleanbit** [zmeyc/telegram-bot-swift#115]
Ubuntu 20.04.1 LTS
Swift 5.3.2-RELEASE-ubuntu20.04
SDK Version: Latest

```Arguments.scanRestOfString()``` will always return empty string on Linux due to the differences in SDK usage. ```scanOfTheRestOfString()``` will call Scanner.scanUpToString() on Linux with the parameter ```""``` (empty string), however see this [line](https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/ScannerAPI.swift#L144), where empty string as a parameter will always return nil.

Calling ```context.args.scanner.scanUpToCharacters(from: .newLines)``` instead, fixes this issue.

**Comment by nerzh** [comment]
it seems they don't support it, maybe you try my package for Vapor https://github.com/nerzh/telegram-vapor-bot

**Comment by zmeyc** [comment]
@cleanbit Thank you for reporting the issue! This should now be fixed by https://github.com/rapierorg/telegram-bot-swift/pull/122
