### ISSUE TITLE
rangeOfString function not working

### ISSUE THREAD

**Issue by simonnarang** [zmeyc/telegram-bot-swift#3]
I am unable to call the `rangeOfString` function for the `command` string.
The error I get is `value of type 'String' has no member 'rangeOfString'`
I don't know why this is happening, I am using swift 2.2 snapshot 4-12 and it runs fine in playground

**Comment by zmeyc** [comment]
In Swift 3 it's range(of: string).

**Comment by zmeyc** [comment]
Btw, I fixed a lot of stuff in 0.4.1, please upgrade. I pushed the changes today. Docs are obsolete now, but Examples/ should be in working state.

**Comment by simonnarang** [comment]
🙏 Thank you so much
