### ISSUE TITLE
editMessageText / editMessageReplyMarkup methods always return "bad request"

### ISSUE THREAD

**Issue by iyumeg** [zmeyc/telegram-bot-swift#31]
I try sync/async, try to write "chat_id" and "message_id", but its always return "bad request"

P.S. Didn't try to use in "Inline Mode".

**Comment by cipi1965** [comment]
In dev branch this works, @zmeyc i think you can close this issue

**Comment by zmeyc** [comment]
Thanks! @iyumeg please reopen if this is still reproduced.
