### ISSUE TITLE
Callback doesn't work because can't read data

### ISSUE THREAD

**Issue by savelii** [zmeyc/telegram-bot-swift#33]
Hey, what the idea behind this pull request?
https://github.com/zmeyc/telegram-bot-swift/pull/30/commits/b442d6763b437ee9a825425aaebcc494233c0bd0

Because of it example stop working
https://github.com/zmeyc/telegram-bot-swift/blob/master/Examples/shopster-bot/Sources/shopster-bot/Controllers/MainController.swift
```
  // "toggle 1234567"
        guard context.args.scanWord() == "toggle" else { return false }
        guard let itemId = context.args.scanInt64() else { return false }
```
args is empty and always no reaction on inline keyboard press

**Comment by zmeyc** [comment]
Hi! Initially, if text was missing `args` were initialized with callback_query.data as a fallback.
This allowed to use router for callback_data:
```
router["someCallbackData"] = { }
```
 
But this approach had two problems:

-  router treats args as an abbreviation. For example, if "a" is sent as callback_query.data, it could trigger totally unrelated router["about"] command.
- user could simulate callback_query.data by sending it as plain text to the bot.

So, we removed the fallback. Now this form should be used instead:
```
router[.callback_query(data: "someCallbackData")] = { }
```

`args` should be replaced with `context.update.callback_query?.data`

I forgot to fix the example, thanks!

**Comment by zmeyc** [comment]
Fixed in dev branch: https://github.com/zmeyc/telegram-bot-swift/commit/8295ef42eabe50c13aec6f734f4efe69b809fc98
