### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by funky-monkey** [zmeyc/telegram-bot-swift#63]
I'd love to see a version that is compatible with Swift 4.0+
Any change that will happen?

Kind regards, 
Sidney

**Comment by zmeyc** [comment]
I haven't tried, but should be easy to adapt. Try the `dev` branch.

**Comment by cipi1965** [comment]
`dev` branch is updated to Swift 4, it's just missing API 4.0 and 4.1 (Telegram Passport) as i didn't have time to update it
