### ISSUE TITLE
Can't run and build hello_bot

### ISSUE THREAD

**Issue by MiladFaridnia** [zmeyc/telegram-bot-swift#64]
I followed the steps mentioned in your docs to run sample projects but I get this error: 
/

> Users/milad/Documents/TelegramBot/t2/telegram-bot-swift/Examples/hello-bot/.build/checkouts/SwiftyJSON.git-1052556473322378765/Source/SwiftyJSON.swift:406:26: error: use of undeclared type '_Incrementable'
> public struct JSONIndex: _Incrementable, Equatable, Comparable {
>                          ^~~~~~~~~~~~~~
> 
I don't know how to fix this. could you please help me ?

**Comment by cipi1965** [comment]
Are you using `dev` branch? Master branch is still Swift 3 (or 2 maybe) and unmaintained

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MiladFaridnia** [comment]
Yes, I was using Master. Switching to dev solved the problem.
