### ISSUE TITLE
Error when building with swift package manager

### ISSUE THREAD

**Issue by iComputerfreak** [zmeyc/telegram-bot-swift#75]
When building a new project using `swift build` with your SDK as a dependency, I get this error: https://pastebin.com/0rpzMgFi

This is my `Package.swift`: https://pastebin.com/FDPg2tzE

I was first using Swift 4.2.1 but also tried updating to Swift 5.0.1, which didn't help.

My `main.swift` only contains these two lines:

```
import TelegramBotSDK

print("Hello, world!")
```

**Comment by cipi1965** [comment]
Are you using macOS or Linux?

**Comment by iComputerfreak** [comment]
I am using Ubuntu 16.04

**Comment by cipi1965** [comment]
You should install `libcurl4-openssl-dev` package

**Comment by iComputerfreak** [comment]
Thank you, that was it.

**Comment by cipi1965** [comment]
You're welcome :)

**Comment by iComputerfreak** [comment]
You should maybe put that in the README.md, so others will see

**Comment by cipi1965** [comment]
Done thank you
