### ISSUE TITLE
Swift Build Error at Linux

### ISSUE THREAD

**Issue by ozyab** [zmeyc/telegram-bot-swift#96]
Works Fine at MacOS, but I get an error on Linux:
```
Sources/TelegramBotSDK/SwiftyJSON/SwiftyJSON.swift:1547:30: error: ambiguous use of operator '<' 
return lhs.rawNumber < rhs.rawNumber
```
Swift 5.1.3
Ubuntu 16.04.6 LTS

It looks like SwiftyJSON issue [#1038](https://github.com/SwiftyJSON/SwiftyJSON/issues/1038)

**Comment by tilucasoli** [comment]
How do you solved it?

**Comment by zmeyc** [comment]
@ozyab @tilucasoli Please use latest version (v2.1.0+) which uses Codable instead of SwiftyJSON. Feel free to re-open the issue if you'll still have any issues.
