### ISSUE TITLE
Bot Not Sending Out Messages

### ISSUE THREAD

**Issue by tanwei0319** [zmeyc/telegram-bot-swift#99]
I can see in the logs that `sendMessage` is called but my Telegram bot did not actually send out the message. This is a snippet of my code:

```Swift
while let update = bot.nextUpdateSync() {
    if let message = update.message, let text = message.text, let from = message.from {
        let id = ChatId.chat(message.chat.id)
        bot.sendMessageSync(chatId: id, text: "say what \(text)")
        bot.sendMessageAsync(chatId: id, text: "CAN SEND PLEASE")
    }
}
```

I've tried manually hitting the send message API on web with my bot token and chat id and it worked, the bot did send the text `TestReply`:
```
https://api.telegram.org/bot<MY_BOT_TOKEN>/sendMessage?chat_id=<CHAT_ID>&text=TestReply
```

**Comment by cipi1965** [comment]
It works for me, can you see if there's any message in the log?

**Comment by zmeyc** [comment]
@tanwei0319 I also checked that it's working, please reopen if you still observe this problem.
